### PR TITLE
Triangles Pattern

### PR DESCRIPTION
**Pull request by ashu273k**
All Pattern problem related with triangles

### CODE REVIEW

**Comment by Student-PrangyaParamita** [comment]
Thank you for your contribution.

**Comment by ashu273k** [comment]
If possible can you label it as Hactober accepted😅, as it will be counted
as my marks in web development.

**Comment by Student-PrangyaParamita** [comment]
Is it ok now!

**Comment by ashu273k** [comment]
Nope it still saying that your repo is not participating in hactober fest.

**Pull request merged**
